### ISSUE TITLE
Problema no executeRequest

### ISSUE THREAD

**Issue by samuellionsoft** [olxbr/olx-api-client#1]
Olá, 
estou tentando fazer a integração e autenticação usando sua API.
Ele esta pegando o json corretamente,
Gera o link corretamente, e redireciona para eu autenticar, e consigo autenticar no site da OLX.
Então ele retorna na url corretamente, só que ao ele pegar o código para enviar via CURL e receber o token, ele retorna false.
No método executeRequest, o $response retorna 
`bool(false)`
e o $result retorna 
`array(4) { ["header"]=> bool(false) ["body"]=> bool(false) ["http_code"]=> int(0) ["last_url"]=> string(35) "https://auth.olx.com.br/oauth/token" }`

**Comment by vitormattos** [comment]
Olá Samuel,

Você possui conta premium e as chaves de acesso a API?
