### ISSUE TITLE
BAD REQUEST - /autoupload/import

### ISSUE THREAD

**Issue by RafasTavares** [olxbr/olx-api-client#6]
Olá, por getileza, estou realizando uma integração com o serviço da olx e não consigo importar meus anuncios. Tenho sempre um Bad Request.  
Pode me ajudar?
```
PUT - https://apps.olx.com.br/autoupload/import
{  
   "access_token":"meu token",
   "ad_list":[
      {  
         "id":"546",
         "operation":"insert",
         "category":2020,
         "subject":"Carro Novo",
         "body":"Corpo do anúnucio",
         "phone":0,
         "type":"null",
         "price":10500,
         "zipcode":"24230090",
         "params": {  
         	"regdate": "2001", 
         	"gearbox": "2",  
         	"fuel": "3",  
         	"cartype": "2",  
         	"mileage": "1",  
         	"doors": "1",  
         	"end_tag": "1",  
         	"car_features": [  "1",  "2"  ] 
        }
    }]
}
```

**Comment by RafasTavares** [comment]
Existe outra documentação além dessa: [LINK](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwisgYi-6eDfAhWBj5AKHaXcDeoQFjAAegQICRAC&url=https%3A%2F%2Folxbrasil.zendesk.com%2Fhc%2Fpt-br%2Farticle_attachments%2F360007789974%2FAPI_OLX_2018.pdf&usg=AOvVaw21dJO8-iORvQZDTdYFKWXB)[]

**Comment by Script-mania** [comment]
Conseguiu resolver! Estou com o mesmo problema.
